server:
  port: 8282
logging.level.org.springframework: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5670
    username: admin
    password: admin

application:
  queues:
    contractCreate: contract.create
    contractEvent: contract.event
  httpClient:
    url: http://localhost:8285/status