version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5670:5672
      - 15670:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin